name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy WireGuard
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "创建 fly.toml 配置文件..."
          cat > fly.toml <<EOF
app = "wg-${{ github.run_id }}"
primary_region = "hkg"

[build]
  image = "fscarmen/flyio-wireguard"

[env]
  PEER_NAME = "client1"
  WG_PORT = "51820"
EOF

          echo "登录 fly.io..."
          echo "${{ secrets.FLY_API_TOKEN }}" | flyctl auth token

          echo "部署到 fly.io..."
          flyctl deploy --remote-only

          echo "部署完成，获取配置..."
          flyctl ssh console -C "cat /config/peer_client1.conf"
